[package]
name = "mageFlag"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3"
image = "0.25"
palette = "0.7"
winreg = "0.52"
eframe = "0.27"
egui = "0.27"
chrono = "0.4.41"

[build]
rustflags = ["-C", "link-args=/SUBSYSTEM:WINDOWS"]

[dev-dependencies]
clippy = "0.0.302"
