name: Windows Release Build

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  build:
    name: Build Windows .exe
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable

      - name: Build release
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mageFlag.exe
          path: target/release/mageFlag.exe

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: mageFlag.exe
          path: .

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: mageFlag.exe

